### ISSUE TITLE
Updating integration duplicates all sensors

### ISSUE THREAD

**Issue by Johanneke** [xirixiz/homeassistant-afvalwijzer#406]
### The problem

I just updated the integration to 2025.03.02, and all sensors provided by the integration were duplicated. The old sensors were "no longer provided by the integration", and the new sensors had the same entity id but suffixed with "_2".

### Version of afvalwijzer integration having the issue?

2025.03.02

### Version of Home Assistant Core having the issue?

2025.3.4

### Anything in the logs that might be useful for us?

```txt

```

**Comment by maxxie85** [comment]
I already have_3 sensors. Was wondering why it wasn't working anymore.

**Comment by YannickvanVugt** [comment]
As far as I am aware this happens almost every bigger update of the integration, not smaller ones when just a provider is added. I have seen it happening twice before, may would've been fixed by now, this 3rd time I wanted to create a bug report as well.
Thanks for creating this, when I have some more time I may try to have a look what causes it as well...

**Comment by Johanneke** [comment]
Yeah, I've seen it happen before, but now decided it was time for a report :)

**Comment by xirixiz** [comment]
I know what happened here. Apologies for the inconvenience.

I had to make some breaking changes recently. These were the last breaking modifications for now. However, there is still an issue with date formatting currently, which I will resolve today.

From now on I`ll make use of pre-releases for some time, before actually releasing.
