### ISSUE TITLE
new integration. wont produce sensors for today and day_after_tomorrow?

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#75]
just installed the new version (with copied api_key from before) 

```
  - platform: afvalwijzer
    provider: mijnafvalwijzer                   # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
    api_token: !secret afvalwijzer_api_token    # (required, default = None) can only be requested/provided by the provider!
    zipcode: !secret postcode                   # (required, default = 1111AA)
    housenumber: !secret huisnummer            # (required, default = 11)
    entity_namespace: saver
#    suffix: None                     (optional, default = None)
#    count_today: false               (optional, default = false) to take or not to take Today into account in the next pickup.
#    default_label: Geen              (optional, default = Geen) label if no date found
```
and all is well, only no sensors for today and day_after_tomorrow:

<img width="535" alt="Schermafbeelding 2020-09-16 om 18 03 28" src="https://user-images.githubusercontent.com/33354141/93363102-13fdfb80-f847-11ea-88bc-a0897869037b.png">

of course resulting in all kinds of trouble ;-)

<img width="503" alt="Schermafbeelding 2020-09-16 om 18 04 50" src="https://user-images.githubusercontent.com/33354141/93363161-27a96200-f847-11ea-9b30-5b8c7668b469.png">

quick fix for that is
```
          unknown: /local/afvalwijzer/kliko_geen.png
```
but of course that denies the underlying issue.

please have a look?
thanks

**Comment by xirixiz** [comment]
Ah, i have trash Today and the upcoming days, so I guess setting it to Geen or None is the issue. I'll fix it Tonight 👍🏻.

**Comment by Mariusthvdb** [comment]
cool,
all my template sensors, images and automations are based on the default 'Geen', so please keep that as per config defaults ;-)

btw, since the enduser now is responsible for entering the correct api_key: how to obtain that going forward? ive copied my old one for now, but since it was announced that is going to change, you might have a sentence or 2 about that in the readme?

**Comment by xirixiz** [comment]
Fixed! 

As for the API key, it's not allowed anymore to share/use it and the token is actually meant for people like us scraping some data... 

So for now, this custom_component is only for Python learning purpouses...

**Comment by Mariusthvdb** [comment]
forgive me for holding in, but I think there's an error still.

Ive sensors with value None now, while I adhere to the default, by not stating anything for `default_label:`

according to your readme it should be 'Geen'.

So you either need to change the readme, or he behavior of the sensor.py

**Comment by Expaso** [comment]
Own man.. this is sad news...  Does that mean you will have to revert to a scraper again?
